version: '{build}'
branches:
  only:
  - master
clone_depth: 1
environment:
  GH_TOKEN:
    secure: gttW1WWlrpNJiUevp7Ldp7amYfqpqu7udsozHnSN0hr5OAkIlEz2jAThj0bYJZQ4
build_script:
  - ps: Install-Product node lts
  - cmd: set PATH=C:\Program Files\Git\usr\bin;%PATH%
  - cmd: bash appveyor_build.sh
test: off
deploy: off
